<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PICK RANDOM STUDENT</name>
   <tag></tag>
   <elementGuidId>fc23ae01-1985-42c8-a463-e285a1573330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div/div[3]/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47ee178e-a3fd-4045-b522-f597cf6f0425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PICK RANDOM STUDENT </value>
      <webElementGuid>005d78a1-1dfb-4424-9592-33b6c73f8d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;rubick px-5 sm:px-6 py-5 before:content-[''] before:bg-gradient-to-b before:from-theme-1 before:to-theme-2 dark:before:from-darkmode-800 dark:before:to-darkmode-800 before:fixed before:inset-0 before:z-[-1] bg-[#153163]&quot;]/div[@class=&quot;mt-[4.7rem] flex md:mt-0&quot;]/div[@class=&quot;md:max-w-auto min-h-screen min-w-0 max-w-full flex-1 rounded-[30px] px-4 pb-10 before:block before:h-px before:w-full before:content-[''] dark:bg-darkmode-700 md:px-[22px]&quot;]/div[@class=&quot;pt-4 overflow-y-auto h-screen scrollbar-hidden&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;flex justify-center mt-4&quot;]/div[@class=&quot;flex flex-col space-y-1 justify-center items-center mt-4 w-[300px]&quot;]/button[@class=&quot;transition duration-200 border shadow-sm inline-flex items-center justify-center rounded-md font-medium cursor-pointer focus:ring-4 focus:ring-primary focus:ring-opacity-20 focus-visible:outline-none dark:focus:ring-slate-700 dark:focus:ring-opacity-50 [&amp;:hover:not(:disabled)]:bg-opacity-90 [&amp;:hover:not(:disabled)]:border-opacity-90 [&amp;:not(button)]:text-center disabled:opacity-70 disabled:cursor-not-allowed button-primary border-[#346edd] text-white dark:border-primary px-2 py-1 mr-2 mt-2&quot;]/div[1]</value>
      <webElementGuid>ed412bd9-b950-4b58-a16c-7757297d83fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div/div[3]/div/button/div</value>
      <webElementGuid>16121f13-985c-4798-abc2-0a9188b195ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Randomizer'])[2]/following::div[6]</value>
      <webElementGuid>ea97c623-6b11-457b-9de3-a5e23f9b8197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Randomizer'])[1]/following::div[21]</value>
      <webElementGuid>704aca78-f8e1-4361-abcb-5dcd6f6a1080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PICK RANDOM STUDENT']/parent::*</value>
      <webElementGuid>690379ea-bb02-4045-8f97-c3dc812722ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>5f8d48f3-4767-4d96-97f8-83f8a043cdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' PICK RANDOM STUDENT ' or . = ' PICK RANDOM STUDENT ')]</value>
      <webElementGuid>4fb05328-11e9-43e5-b558-f8aeb1d58c78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
