<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_POST</name>
   <tag></tag>
   <elementGuidId>c6a0afd1-a55b-4889-a62d-bef04271dab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[3]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf1b4ded-ab01-43ff-a282-171656a9cdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> POST </value>
      <webElementGuid>a0e0cbc9-4b30-410f-bd21-0fafd62c6faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;rubick px-5 sm:px-6 py-5 before:content-[''] before:bg-gradient-to-b before:from-theme-1 before:to-theme-2 dark:before:from-darkmode-800 dark:before:to-darkmode-800 before:fixed before:inset-0 before:z-[-1] bg-[#153163]&quot;]/div[@class=&quot;mt-[4.7rem] flex md:mt-0&quot;]/div[@class=&quot;md:max-w-auto min-h-screen min-w-0 max-w-full flex-1 rounded-[30px] px-4 pb-10 before:block before:h-px before:w-full before:content-[''] dark:bg-darkmode-700 md:px-[22px]&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;flex flex-col items-center space-y-6 mt-5&quot;]/div[@class=&quot;flex flex-col w-[480px] p-4 box card-default-class&quot;]/div[@class=&quot;flex justify-end mt-4 border-t-[0.5px] border-neutral-300 pt-2&quot;]/button[@class=&quot;transition duration-200 border shadow-sm inline-flex items-center justify-center rounded-md font-medium cursor-pointer focus:ring-4 focus:ring-primary focus:ring-opacity-20 focus-visible:outline-none dark:focus:ring-slate-700 dark:focus:ring-opacity-50 [&amp;:hover:not(:disabled)]:bg-opacity-90 [&amp;:hover:not(:disabled)]:border-opacity-90 [&amp;:not(button)]:text-center disabled:opacity-70 disabled:cursor-not-allowed text-xs py-1.5 button-primary border-[#346edd] text-white dark:border-primary px-4&quot;]/div[1]</value>
      <webElementGuid>ef3e79c0-b0ca-4202-9bea-a3deb85d8640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[3]/button/div</value>
      <webElementGuid>a3613b95-9e4d-46d3-a0e5-c1c3019345f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moments'])[2]/following::div[9]</value>
      <webElementGuid>b7f96ccd-0f75-4e48-8f17-943d88a2806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moments'])[1]/following::div[23]</value>
      <webElementGuid>aa23fdc1-c2d6-4eb8-80df-3060d97822c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andres as'])[1]/preceding::div[2]</value>
      <webElementGuid>9bbc48ac-b7d3-432f-a8e3-289c65cd1097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show all'])[1]/preceding::div[11]</value>
      <webElementGuid>2bd9846d-7e13-406f-b0fc-6ed092e02649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='POST']/parent::*</value>
      <webElementGuid>0bd271af-9dc5-4889-b018-5da8169159e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>86fab1e6-03e4-4ade-a3f3-72a568b5b50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' POST ' or . = ' POST ')]</value>
      <webElementGuid>0482e43a-dd25-4839-9375-0d96d25ee428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
