<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__box rounded-md w-full px-3 py-2 bloc_2bc69b_1</name>
   <tag></tag>
   <elementGuidId>9e88f865-d09b-40d1-b2fd-7b7023b7e98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.box.rounded-md.w-full.px-3.py-2.block.custom-input-default-class.flatpickr-input.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ea5347b-7143-4b80-9634-522758da88df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28eadcd9-9668-4438-a9e7-3ae7e9e3d6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c0ea603-7251-4527-865d-de97968a04d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box rounded-md w-full px-3 py-2 block custom-input-default-class flatpickr-input active</value>
      <webElementGuid>8d0ee978-4e4b-47c7-961b-1a118c3cf995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minimumdate</name>
      <type>Main</type>
      <value>Tue Oct 22 2024 02:36:59 GMT+0800 (Philippine Standard Time)</value>
      <webElementGuid>3771f46c-bcf8-44df-9ddf-c944bf181a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>cf30d3cb-2204-446f-80a8-0101b994147e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>18b89b73-dc48-4d40-a8e3-8fce5de7cc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-18&quot;)/div[@class=&quot;px-5&quot;]/div[1]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;box rounded-md w-full px-3 py-2 block custom-input-default-class flatpickr-input active&quot;]</value>
      <webElementGuid>b05182ed-8bb1-428f-8f21-a633930871c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>a1ccf2fb-9cbe-43c1-9824-6e56308483f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-18']/div[2]/div/div/div[2]/div[4]/input</value>
      <webElementGuid>34264631-c610-4497-81f6-c7882f3f87ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>10c3aa84-627f-4f8c-9eb8-d5f16fc7cc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'End date']</value>
      <webElementGuid>1e57f63f-33ce-40c7-97d2-45bbb0d80970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
