<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__box rounded-md w-full px-3 py-2 bloc_2bc69b</name>
   <tag></tag>
   <elementGuidId>91f20357-026b-4cd8-a2bf-624c56a30659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.box.rounded-md.w-full.px-3.py-2.block.custom-input-default-class.flatpickr-input.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79288dbc-d59a-493f-b48d-f2c8e939d08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab1b9318-ace1-4b47-99ff-4114d8c6061e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a75e935f-71b3-441f-b5e2-a3a1caa30354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box rounded-md w-full px-3 py-2 block custom-input-default-class flatpickr-input active</value>
      <webElementGuid>58db580d-3f0e-4e67-b12f-8c56039a931b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minimumdate</name>
      <type>Main</type>
      <value>Tue Oct 22 2024 02:36:59 GMT+0800 (Philippine Standard Time)</value>
      <webElementGuid>1d635517-cf52-4903-9626-129d4f770551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>d7131b89-cf7d-46d4-be73-8347708266db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>555f3642-f9a3-4326-8518-dc07440faf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-18&quot;)/div[@class=&quot;px-5&quot;]/div[1]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;box rounded-md w-full px-3 py-2 block custom-input-default-class flatpickr-input active&quot;]</value>
      <webElementGuid>71d25d09-bc83-49a9-aa59-669da29b6f67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>ef016932-3e04-404a-9813-e729a479234a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-18']/div[2]/div/div/div[2]/div[3]/input</value>
      <webElementGuid>a5616616-ed4a-433a-8428-5b487e698f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ffd69207-2262-4ff8-872b-6986643b0846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Start date']</value>
      <webElementGuid>6b5ee5a1-06a8-48f5-87b7-088c4a1ac70d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
