<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__items-placeholder</name>
   <tag></tag>
   <elementGuidId>7fd5d194-8fa1-4033-ad95-996eb5ab7262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.items-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tomselect-1-ts-control']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>720dceb4-bbee-424e-8866-b7083e6c5ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-placeholder</value>
      <webElementGuid>b519fee2-22c8-41d4-8f14-a1f202de455a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>23d8a587-245e-4763-9314-9416d12b26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select event</value>
      <webElementGuid>eab94d7c-546d-44b0-8373-bd1ed0589ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1-ts-control&quot;)/input[@class=&quot;items-placeholder&quot;]</value>
      <webElementGuid>d06af0dc-adb8-402e-9fa9-2188cc6a7c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tomselect-1-ts-control']/input</value>
      <webElementGuid>758ccad4-01ab-4e4d-bac6-9fea40b4b677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>22c99250-4abd-4662-bf42-121db1958576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Select event']</value>
      <webElementGuid>fbd99594-0d78-46bc-8d91-aa9d79c7e006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
