<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an option School EventPersona_e622a4</name>
   <tag></tag>
   <elementGuidId>77830f15-9cc4-4eb6-88fb-2a4ea83dbe64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tomselect-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c1ebc04a-b873-4510-bf61-6f0d19fa1706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tom-select border-0 w-full text-sm mt-2 tomselected ts-hidden-accessible</value>
      <webElementGuid>cfcf7238-ea2f-4882-a75c-d5d62d219cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>_7a6st78rh</value>
      <webElementGuid>d9efcfbf-c238-427e-9279-ce1461119126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-class</name>
      <type>Main</type>
      <value>tom-select border-0 w-full text-sm mt-2</value>
      <webElementGuid>3df03332-0e2d-49d0-9026-50241806e269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1</value>
      <webElementGuid>3050f822-1be3-445e-a009-348de517ea09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>098a17a0-21e1-4332-9941-4c9f9cd81e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select an option School EventPersonalHoliday</value>
      <webElementGuid>edcc85dc-651f-4c7d-a444-9421e88400ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1&quot;)</value>
      <webElementGuid>18b25049-9d77-427f-aad4-23712a31ab39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tomselect-1']</value>
      <webElementGuid>55dcfc1e-67a7-4a77-95a6-5d8b2d7b80bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-18']/div[2]/div/div/div[2]/div[2]/select[2]</value>
      <webElementGuid>57920739-f4ed-4ce7-890d-9929320bc8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[2]</value>
      <webElementGuid>a9a27efb-8d67-4323-b94c-729efe5a3a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[3]/preceding::select[1]</value>
      <webElementGuid>a799ac29-3862-41e0-b2cb-d60c553d0599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[4]/preceding::select[1]</value>
      <webElementGuid>fb3c5d5e-24c3-4ac0-9f0f-272f40c433d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>45294619-4a6c-4a78-8c64-da18ee98cdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tomselect-1' and (text() = ' Select an option School EventPersonalHoliday' or . = ' Select an option School EventPersonalHoliday')]</value>
      <webElementGuid>57655634-ea81-4795-9358-1994ced9936b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
