<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an option HolidayPersonalScho_22eda6</name>
   <tag></tag>
   <elementGuidId>cdedbe00-3dbf-400b-a20e-7d446dd03238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tomselect-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23a95ce4-6a08-4c59-b417-1b909c20a773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tom-select border-0 w-full text-sm mt-2 tomselected ts-hidden-accessible</value>
      <webElementGuid>3ab13509-3a39-4763-bd56-43d82476121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>_02wrrhwtk</value>
      <webElementGuid>8df8883e-3c32-4aae-9d11-45c3caad4052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-class</name>
      <type>Main</type>
      <value>tom-select border-0 w-full text-sm mt-2</value>
      <webElementGuid>eb64b171-6ed9-40a0-83ee-73a9f1f58e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1</value>
      <webElementGuid>55d74196-1642-43d0-afa0-188026ec7b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>520db555-05c9-4615-b797-02e730690f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select an option HolidayPersonalSchool Event</value>
      <webElementGuid>0948f569-86fb-45ec-9afb-bb7c49c58ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1&quot;)</value>
      <webElementGuid>726d08df-f77e-4314-bb10-3e298b9034a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tomselect-1']</value>
      <webElementGuid>b876f23d-53a4-4211-8cc0-93167f768126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-18']/div[2]/div/div/div[2]/div[2]/select[2]</value>
      <webElementGuid>f7d96c03-d937-4504-b243-dec195360cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[2]</value>
      <webElementGuid>50dfc65c-7248-4938-abbb-d43df797a8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Event'])[3]/preceding::select[1]</value>
      <webElementGuid>ace540e4-0542-4269-8b83-6887f2bd47a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[3]/preceding::select[1]</value>
      <webElementGuid>deefec22-325d-4136-98e3-ca56da21208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>3fe3e04b-0af7-483c-975b-6310d74f0bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tomselect-1' and (text() = ' Select an option HolidayPersonalSchool Event' or . = ' Select an option HolidayPersonalSchool Event')]</value>
      <webElementGuid>2b5ff47d-a223-4ecc-907d-972143df3ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
