<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an option HolidaySchool Event_3c80b6</name>
   <tag></tag>
   <elementGuidId>1d58a5a2-5757-4412-864b-7a0d7d17b244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tomselect-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tomselect-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ab784ab8-c1e4-45c9-9b92-9ce3ea65cd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tom-select border-0 w-full text-sm mt-2 tomselected ts-hidden-accessible</value>
      <webElementGuid>be44ec22-c105-4623-945f-9a0518748c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>_k43jcmxgz</value>
      <webElementGuid>2ad81642-0e0f-4a15-849e-d4c16910967a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-class</name>
      <type>Main</type>
      <value>tom-select border-0 w-full text-sm mt-2</value>
      <webElementGuid>8b3ed95d-1ba8-46a9-967b-1e356ed373f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tomselect-1</value>
      <webElementGuid>414e2fe4-cc47-44fa-8522-786adc2eb5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3d350398-f821-4db9-a954-717a37f0570d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select an option HolidaySchool EventPersonal</value>
      <webElementGuid>61eb42e4-0cf7-4740-91e3-3e9bb16755d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tomselect-1&quot;)</value>
      <webElementGuid>29b7d36b-3ea0-4c4c-9e27-a1354772add7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tomselect-1']</value>
      <webElementGuid>6f2531d1-a045-4846-a30b-aac4cf3ceeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-18']/div[2]/div/div/div[2]/div[2]/select[2]</value>
      <webElementGuid>a571acd5-f0ff-4d7b-a1be-c479b89a1347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[2]</value>
      <webElementGuid>54bd6e51-fbc8-4259-94f8-0cb72800246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal'])[3]/preceding::select[1]</value>
      <webElementGuid>cf738b43-4e6d-4838-9b68-f2c49d99b2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[3]/preceding::select[1]</value>
      <webElementGuid>dbe9b6e6-b4e1-4a4f-827f-4ba89b303134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>c3835d4d-2d33-41af-b110-1e6ab5a45f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tomselect-1' and (text() = ' Select an option HolidaySchool EventPersonal' or . = ' Select an option HolidaySchool EventPersonal')]</value>
      <webElementGuid>ee6a6181-2c04-4c61-aa85-d3ffde587149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
